package org.usefultoys.slf4j.watcher;

import org.awaitility.Awaitility;
import org.junit.jupiter.api.*;
import org.slf4j.LoggerFactory;
import org.slf4j.impl.TestLogger;
import org.usefultoys.slf4j.SessionConfig;
import org.usefultoys.slf4j.SystemConfig;

import java.nio.charset.Charset;
import java.util.Timer;
import java.util.TimerTask;
import java.util.concurrent.ScheduledExecutorService;
import java.util.concurrent.ScheduledFuture;
import java.util.concurrent.TimeUnit;

import static org.junit.jupiter.api.Assertions.*;

class WatcherSingletonTest {

    @BeforeAll
    static void validate() {
        assertEquals(Charset.defaultCharset().name(), SessionConfig.charset, "Test requires SessionConfig.charset = default charset");
    }

    @BeforeEach
    void resetWatcherConfigBeforeEach() {
        // Reinitialize WatcherConfig to ensure clean configuration before each test
        WatcherConfig.reset();
        SessionConfig.reset();
        SystemConfig.reset();
    }

    @AfterAll
    static void resetWatcherConfigAfterAll() {
        // Reinitialize WatcherConfig to ensure clean configuration for further tests
        WatcherConfig.reset();
        SessionConfig.reset();
        SystemConfig.reset();
    }

    private TestLogger testLogger = (TestLogger) LoggerFactory.getLogger(WatcherConfig.name);;

    @BeforeEach
    void setupLogger() {
        testLogger.setEnabled(true);
        testLogger.clearEvents();
    }

    @AfterEach
    void clearLogger() {
        testLogger.setEnabled(true);
        testLogger.clearEvents();
    }

    @AfterEach
    void stopAllWatchers() {
        WatcherSingleton.stopDefaultWatcherExecutor();
        WatcherSingleton.stopDefaultWatcherTimer();
    }

    @Test
    void shouldLogStatusWithExecutor() {
        // Arrange
        WatcherConfig.delayMilliseconds = 200;
        WatcherConfig.periodMilliseconds = 200;

        assertNull(WatcherSingleton.defaultWatcherExecutor);
        assertNull(WatcherSingleton.scheduledDefaultWatcher);

        assertDoesNotThrow(() -> WatcherSingleton.startDefaultWatcherExecutor());
        assertNotNull(WatcherSingleton.defaultWatcherExecutor);
        assertNotNull(WatcherSingleton.scheduledDefaultWatcher);

        final ScheduledExecutorService executor = WatcherSingleton.defaultWatcherExecutor;
        final ScheduledFuture<?> watcher = WatcherSingleton.scheduledDefaultWatcher;

        // Must support calling the start method multiple times without disruption
        assertDoesNotThrow(() -> WatcherSingleton.startDefaultWatcherExecutor());
        assertEquals(executor, WatcherSingleton.defaultWatcherExecutor);
        assertEquals(watcher, WatcherSingleton.scheduledDefaultWatcher);

        // Wait for log messages to be generated by scheduled task
        Awaitility.await().atMost(2, TimeUnit.SECONDS).until(() ->
                testLogger.getEventCount() > 0
        );

        assertTrue(testLogger.getEventCount() == 1);
        assertTrue(testLogger.getEvent(0).getFormattedMessage().contains("Memory:"));

        assertDoesNotThrow(() -> WatcherSingleton.stopDefaultWatcherExecutor());
        assertNull(WatcherSingleton.defaultWatcherExecutor);
        assertNull(WatcherSingleton.scheduledDefaultWatcher);

        // Must support calling the stop method multiple times without disruption
        assertDoesNotThrow(() -> WatcherSingleton.stopDefaultWatcherExecutor());
        assertNull(WatcherSingleton.defaultWatcherExecutor);
        assertNull(WatcherSingleton.scheduledDefaultWatcher);
    }

    @Test
    void shouldLogStatusWithTimer() {
        // Arrange
        WatcherConfig.delayMilliseconds = 200;
        WatcherConfig.periodMilliseconds = 200;

        assertNull(WatcherSingleton.defaultWatcherTimer);
        assertNull(WatcherSingleton.defaultWatcherTask);

        assertDoesNotThrow(() -> WatcherSingleton.startDefaultWatcherTimer());
        assertNotNull(WatcherSingleton.defaultWatcherTimer);
        assertNotNull(WatcherSingleton.defaultWatcherTask);
        final Timer timer = WatcherSingleton.defaultWatcherTimer;
        final TimerTask watcher = WatcherSingleton.defaultWatcherTask;

        // Must support calling the start method multiple times without disruption
        assertDoesNotThrow(() -> WatcherSingleton.startDefaultWatcherTimer());
        assertEquals(timer, WatcherSingleton.defaultWatcherTimer);
        assertEquals(watcher, WatcherSingleton.defaultWatcherTask);

        // Wait for log messages to be generated by scheduled task
        Awaitility.await().atMost(2, TimeUnit.SECONDS).until(() ->
                testLogger.getEventCount() > 0
        );

        assertTrue(testLogger.getEventCount() == 1);
        assertTrue(testLogger.getEvent(0).getFormattedMessage().contains("Memory:"));

        assertDoesNotThrow(() -> WatcherSingleton.stopDefaultWatcherTimer());
        assertNull(WatcherSingleton.defaultWatcherTimer);
        assertNull(WatcherSingleton.defaultWatcherTask);

        // Must support calling the stop method multiple times without disruption
        assertDoesNotThrow(() -> WatcherSingleton.stopDefaultWatcherTimer());
        assertNull(WatcherSingleton.defaultWatcherTimer);
        assertNull(WatcherSingleton.defaultWatcherTask);
    }
}
