/*
 * Copyright 2025 Daniel Felix Ferber
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package org.usefultoys.slf4j.logback;

import ch.qos.logback.classic.pattern.ClassicConverter;
import ch.qos.logback.classic.spi.ILoggingEvent;
import org.slf4j.Marker;
import org.usefultoys.slf4j.meter.Markers;

import java.util.HashMap;
import java.util.Map;

/**
 * A Logback converter that extracts and formats a concise status string based on the
 * SLF4J {@link Marker} associated with a logging event.
 * <p>
 * This converter is used to display a short, human-readable status in log messages,
 * particularly for events generated by `slf4j-toys` components.
 * For data messages (e.g., {@code DATA_*} markers), it returns an empty string to keep the log clean.
 *
 * @author Daniel Felix Ferber
 * @see Markers
 */
public class StatusConverter extends ClassicConverter {
    private static final Map<Marker, String> STATUS_MAP = new HashMap<>();

    static {
        STATUS_MAP.put(Markers.MSG_START, "START");
        STATUS_MAP.put(Markers.MSG_PROGRESS, "PROGR");
        STATUS_MAP.put(Markers.MSG_OK, "OK");
        STATUS_MAP.put(Markers.MSG_SLOW_OK, "SLOW");
        STATUS_MAP.put(Markers.MSG_REJECT, "REJECT");
        STATUS_MAP.put(Markers.MSG_FAIL, "FAIL");
        STATUS_MAP.put(Markers.DATA_START, "");
        STATUS_MAP.put(Markers.DATA_PROGRESS, "");
        STATUS_MAP.put(Markers.DATA_OK, "");
        STATUS_MAP.put(Markers.DATA_SLOW_OK, "");
        STATUS_MAP.put(Markers.DATA_REJECT, "");
        STATUS_MAP.put(Markers.DATA_FAIL, "");
        STATUS_MAP.put(Markers.BUG, "BUG");
        STATUS_MAP.put(Markers.ILLEGAL, "ILLEGAL");
        STATUS_MAP.put(Markers.INCONSISTENT_START, "INCONSISTENT");
        STATUS_MAP.put(Markers.INCONSISTENT_INCREMENT, "INCONSISTENT");
        STATUS_MAP.put(Markers.INCONSISTENT_PROGRESS, "INCONSISTENT");
        STATUS_MAP.put(Markers.INCONSISTENT_EXCEPTION, "INCONSISTENT");
        STATUS_MAP.put(Markers.INCONSISTENT_REJECT, "INCONSISTENT");
        STATUS_MAP.put(Markers.INCONSISTENT_OK, "INCONSISTENT");
        STATUS_MAP.put(Markers.INCONSISTENT_FAIL, "INCONSISTENT");
        STATUS_MAP.put(Markers.INCONSISTENT_FINALIZED, "INCONSISTENT");
        STATUS_MAP.put(org.usefultoys.slf4j.watcher.Markers.MSG_WATCHER, "WATCHER");
        STATUS_MAP.put(org.usefultoys.slf4j.watcher.Markers.DATA_WATCHER, "");
    }

    /**
     * Converts a logging event's {@link Marker} into a status string.
     *
     * @param event The logging event.
     * @return A string representing the status, or an empty string for data markers.
     */
    @Override
    public String convert(final ILoggingEvent event) {
        final Marker marker = event.getMarker();
        final String statusString = STATUS_MAP.get(marker);
        return statusString != null ? statusString : event.getLevel().toString();
    }
}
