/*
 * Copyright 2025 Daniel Felix Ferber
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package org.usefultoys.jul.mock;

import lombok.Getter;
import lombok.ToString;

import java.text.MessageFormat;
import java.util.ResourceBundle;
import java.util.logging.Level;
import java.util.logging.LogRecord;

/**
 * Represents a single log event captured by {@link MockHandler}.
 * <p>
 * This class holds all details of a logging call, including the logger name, log level, original message,
 * parameters, and optional throwable. It is an immutable wrapper around {@link LogRecord} that provides
 * convenient access to log event data for test assertions.
 * <p>
 * The formatted message is generated by applying Java's {@link MessageFormat} to the message pattern and
 * parameters, following JUL's formatting conventions.
 * <p>
 * Example usage in tests:
 * <pre>{@code
 * MockHandler handler = new MockHandler();
 * MockLogRecord record = handler.getRecord(0);
 * assertEquals(Level.INFO, record.getLevel());
 * assertTrue(record.getFormattedMessage().contains("Expected text"));
 * }</pre>
 * <p>
 * This class is immutable and thread-safe.
 *
 * @author Daniel Felix Ferber
 */
@Getter
@ToString(includeFieldNames = true)
public class MockLogRecord {

    private final String loggerName;
    private final Level level;
    private final String message;
    private final Object[] parameters;
    private final Throwable thrown;
    private final String sourceClassName;
    private final String sourceMethodName;
    private final long millis;
    private final long sequenceNumber;
    private final int threadID;
    private final ResourceBundle resourceBundle;
    private final String resourceBundleName;

    /**
     * Constructs a new MockLogRecord from a JUL LogRecord.
     * <p>
     * This constructor creates an immutable snapshot of the provided LogRecord,
     * capturing all relevant information at the time of logging.
     *
     * @param record the JUL LogRecord to wrap
     */
    public MockLogRecord(final LogRecord record) {
        this.loggerName = record.getLoggerName();
        this.level = record.getLevel();
        this.message = record.getMessage();
        this.parameters = record.getParameters();
        this.thrown = record.getThrown();
        this.sourceClassName = record.getSourceClassName();
        this.sourceMethodName = record.getSourceMethodName();
        this.millis = record.getMillis();
        this.sequenceNumber = record.getSequenceNumber();
        this.threadID = record.getThreadID();
        this.resourceBundle = record.getResourceBundle();
        this.resourceBundleName = record.getResourceBundleName();
    }

    /**
     * Returns the formatted message by applying Java's {@link MessageFormat} to the message and parameters.
     * <p>
     * This method processes the message format string and substitutes placeholders with the provided parameters,
     * following JUL's formatting conventions. If resource bundle localization is available, it is applied first.
     *
     * @return the formatted message string
     */
    public String getFormattedMessage() {
        String msg = message;
        
        if (resourceBundle != null && message != null) {
            try {
                msg = resourceBundle.getString(message);
            } catch (final java.util.MissingResourceException ex) {
                msg = message;
            }
        }
        
        if (parameters != null && parameters.length > 0 && msg != null) {
            try {
                msg = MessageFormat.format(msg, parameters);
            } catch (final Exception ex) {
                return msg;
            }
        }
        
        return msg;
    }
}
