/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package org.usefultoys.slf4j.examples;

import java.util.concurrent.Executor;
import java.util.concurrent.Executors;
import org.usefultoys.slf4j.LoggerFactory;
import org.usefultoys.slf4j.Session;
import org.usefultoys.slf4j.report.Reporter;

/**
 * Demonstrates the default report generated by
 * {@link Session#runDefaultReport()}.
 *
 * @author Daniel Felix Ferber
 */
public class CustomReport2 {

    public static void main(String[] args) {
        System.setProperty("org.slf4j.simpleLogger.defaultLogLevel", "trace");

        Executor executor = Executors.newFixedThreadPool(3);
        Reporter reporter = new Reporter(LoggerFactory.getLogger("customreport"));
        executor.execute(reporter.new ReportPhysicalSystem());
        executor.execute(reporter.new ReportMemory());
    }
}
