/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package org.usefultoys.slf4j.examples;

import java.util.concurrent.Executor;
import java.util.concurrent.Executors;
import org.slf4j.Logger;
import org.usefultoys.slf4j.LoggerFactory;
import org.usefultoys.slf4j.Session;
import org.usefultoys.slf4j.report.Reporter;

/**
 * Demonstrates the default report generated by
 * {@link Session#runDefaultReport()}.
 *
 * @author Daniel Felix Ferber
 */
public class CustomReport1 {

    public static void main(String[] args) {
//        The default report may be customized with system properties, for example:
//        System.setProperty("slf4jtoys.report.networkInterface", "true");
//        System.setProperty("slf4jtoys.report.fileSystem", "true");
        System.setProperty("org.slf4j.simpleLogger.defaultLogLevel", "trace");

        Executor executor = Executors.newFixedThreadPool(3);
        Reporter reporter = new Reporter(LoggerFactory.getLogger("customreport"));
        reporter.logDefaultReports(executor);
    }
}
