/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package org.usefultoys.slf4j.examples;

import org.usefultoys.slf4j.Session;

/**
 * Demonstrates the default report generated by
 * {@link Session#runDefaultReport()}.
 *
 * @author Daniel Felix Ferber
 */
public class DefaultReport {

    public static void main(String[] args) {
//        The default report may be customized with system properties, for example:
//        System.setProperty("slf4jtoys.report.networkInterface", "true");
//        System.setProperty("slf4jtoys.report.fileSystem", "true");
        System.setProperty("org.slf4j.simpleLogger.defaultLogLevel", "trace");

        Session.runDefaultReport();
    }
}
