/*
 * Copyright 2025 Daniel Felix Ferber
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package org.usefultoys.slf4j;

import java.util.Arrays;

/**
 * A custom, artificial throwable used to report invalid library usage.
 * <p>
 * This is an artificial throwable. It is not intended to be thrown in error situations.
 * Instead, it is created and logged as a warning to provide a stack trace that points
 * directly to the client method that made an invalid call to the library. This makes it
 * much easier to locate the source of the incorrect usage.
 * <p>
 * The primary purpose is to manipulate the stack trace to point to the user's code or
 * the first Meter method call, removing the library's internal stack frames. When this
 * throwable is logged, the stack trace will start at the first Meter method call (if available),
 * or at the method that incorrectly used the library, rather than showing internal
 * implementation details.
 */
@SuppressWarnings("ExtendsThrowable")
public class CallerStackTraceThrowable extends Throwable {

    private static final long serialVersionUID = 1L;
    public static final String PACKAGE_NAME = CallerStackTraceThrowable.class.getPackage().getName();
    public static final StackTraceElement[] EMPTY_STACK_TRACE = new StackTraceElement[0];

    public CallerStackTraceThrowable() {
    }

    public CallerStackTraceThrowable(final String message) {
        super(message);
    }

    public CallerStackTraceThrowable(final String message, final Throwable cause) {
        super(message, cause);
    }

    public CallerStackTraceThrowable(final Throwable cause) {
        super(cause);
    }

    public String getApiMethodName() {
        final StackTraceElement[] stacktrace = getStackTrace();
        if (stacktrace.length == 0) {
            return null;
        }
        if (stacktrace[0].getClassName().startsWith(PACKAGE_NAME)) {
            return stacktrace[0].getMethodName();
        }
        return null;
    }
    /**
     * Overrides `fillInStackTrace()` to prevent it from capturing the stack trace again,
     * as it has already been manipulated in the constructor.
     *
     * @return This `Throwable` instance.
     */
    @Override
    public synchronized Throwable fillInStackTrace() {
        final StackTraceElement[] stacktrace = Thread.currentThread().getStackTrace();

        /* Always skip index 0 (Thread.getStackTrace, fillInStackTrace itself and Exception constructor) and start from index 3 */
        int framesToDiscard = 3;

        /* Skip all frames from the CallerStackTraceThrowable and library internals. 
           A proper handling is required while running under stats, since stack trace may be under influence of Mockito 
           additional reflection calls, and the method may be thrown from the test class, which is under the same package,
           but is not considered library itself. */
        while (framesToDiscard < stacktrace.length &&
                (stacktrace[framesToDiscard].getClassName().startsWith(PACKAGE_NAME) ||
                    /* During tests, skip artificial stack trace calls generated by mockito */
                    stacktrace[framesToDiscard].getClassName().contains("org.mockito") ||
                    stacktrace[framesToDiscard].getClassName().contains("sun.reflect") ||
                    stacktrace[framesToDiscard].getClassName().contains("java.lang.invoke") ||
                    stacktrace[framesToDiscard].getClassName().contains("java.lang.reflect")
                 ) &&
                 /* During tests, the test class appears as the same package name, but ist not considered being part of the library itself. */
                ! (stacktrace[framesToDiscard].getClassName().endsWith("Test") ||
                   stacktrace[framesToDiscard].getClassName().endsWith("Tests"))
        ){
            framesToDiscard++;
        }

        if (framesToDiscard == stacktrace.length) {
            /* All stack trace frames are from the library itself. */
            setStackTrace(EMPTY_STACK_TRACE);
        } else if (framesToDiscard == 3) {
            /* No library frames found (only user code), keep all from index 3 onwards */
            setStackTrace(Arrays.copyOfRange(stacktrace, 3, stacktrace.length));
        } else if (stacktrace[framesToDiscard - 1].getClassName().equals(CallerStackTraceThrowable.class.getName())) {
            /* Found exception constructor called directly from user code. */
            setStackTrace(Arrays.copyOfRange(stacktrace, framesToDiscard, stacktrace.length));
        } else {
            /* Library frames found, keep first library frame + all user code.
               Decrease by 1 to include the last library method (API entry point). */
            setStackTrace(Arrays.copyOfRange(stacktrace, framesToDiscard - 1, stacktrace.length));
        }
        return this;
    }
}
